name: Deploy APT repo to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'debs/**'
      - 'scripts/**'
      - 'style.css'
      - '.github/workflows/deploy.yml'
      - 'generate-index.sh'
      - 'CydiaIcon.png'
  workflow_dispatch:

# Cấp quyền cho Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare build dir
        run: |
          rm -rf out && mkdir -p out/repo
          [ -f style.css ] && cp style.css out/ || true
          [ -f CydiaIcon.png ] && cp CydiaIcon.png out/ || true
          if ls debs/*.deb >/dev/null 2>&1; then
            cp debs/*.deb out/repo/
          else
            echo "WARNING: Không tìm thấy debs/*.deb — vẫn deploy nhưng Packages sẽ trống."
          fi

      - name: Install dpkg-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Generate Packages (and gzip)
        run: |
          cd out/repo
          dpkg-scanpackages . /dev/null > Packages
          gzip -fk Packages
          cd -

      - name: Generate index.html (Bootstrap) inline
        run: |
          cat > out/index.html <<'HTML'
          <!doctype html>
          <html lang="vi">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Ninh Repo</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
            <link rel="icon" href="CydiaIcon.png">
          </head>
          <body>
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
              <div class="container">
                <a class="navbar-brand" href="./">Ninh Repo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div id="nav" class="collapse navbar-collapse">
                  <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="packages.html">Packages (viewer)</a></li>
                    <li class="nav-item"><a class="nav-link" href="repo/Packages">/repo/Packages</a></li>
                  </ul>
                </div>
              </div>
            </nav>
            <header class="py-5 bg-light border-bottom">
              <div class="container">
                <h1 class="display-6 fw-bold">Kho APT Repo của Ninh (GitHub Pages)</h1>
                <p class="lead mb-4">Tuyển tập các deb, ipa dành cho hệ IOS cổ, mời anh em <code>vọc</code>.</p>
                <div>
                  <a class="btn btn-primary btn-lg me-2" href="packages.html">Xem Packages</a>
                  <a class="btn btn-outline-secondary btn-lg" href="repo/Packages">Tải Packages</a>
                </div>
              </div>
            </header>
            <main class="container my-5">
              <div class="row g-4">
                <div class="col-md-6">
                  <div class="card h-100 shadow-sm">
                    <div class="card-body">
                      <h5 class="card-title">Thêm repo vào Sileo/Cydia</h5>
                      <pre class="mb-0"><code>https://repo.ninh.us</code></pre>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="card h-100 shadow-sm">
                    <div class="card-body">
                      <h5 class="card-title">File quan trọng</h5>
                      <ul class="mb-0">
                        <li><code>repo/Packages</code> và <code>repo/Packages.gz</code></li>
                        <li><code>.nojekyll</code> ở gốc</li>
                        <li><code>Release</code>, <code>InRelease</code> (nếu bạn ký)</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </main>
            <footer class="py-4 bg-dark text-white-50">
              <div class="container text-center small">© 2025 <a href="/">Ninh Repo</a></div>
            </footer>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
          </body>
          </html>
          HTML

      - name: Generate packages.html (viewer)
        run: |
          cat > out/packages.html <<'HTML'
          <!doctype html>
          <html lang="vi">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Packages Viewer</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
            <style>pre { white-space: pre-wrap; word-wrap: break-word; }</style>
          </head>
          <body>
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
              <div class="container">
                <a class="navbar-brand" href="./">APT Repo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div id="nav" class="collapse navbar-collapse">
                  <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="repo/Packages">Tải Packages</a></li>
                  </ul>
                </div>
              </div>
            </nav>
            <main class="container my-4">
              <h1 class="h4 mb-3">Nội dung Packages</h1>
              <div class="alert alert-info">
                Nếu không thấy nội dung, kiểm tra:
                <ul class="mb-0">
                  <li>Đã sinh <code>repo/Packages</code>?</li>
                  <li>Có file <code>.nojekyll</code> ở gốc?</li>
                  <li>Settings → Pages đã chọn nguồn GitHub Actions?</li>
                </ul>
              </div>
              <div id="status" class="mb-3 text-muted">Đang tải…</div>
              <div class="table-responsive">
                <table class="table table-sm table-striped">
                  <thead><tr>
                    <th>Package</th><th>Version</th><th>Arch</th><th>Size</th><th>Description</th><th>File</th>
                  </tr></thead>
                  <tbody id="pkgBody"><tr><td colspan="6">Đang tải…</td></tr></tbody>
                </table>
              </div>
              <pre class="p-3 bg-light border rounded d-none" id="rawBox"></pre>
            </main>
            <script>
            const PACKAGES_PATH = 'repo/Packages';
            async function loadPackages(){
              const body = document.getElementById('pkgBody');
              const raw  = document.getElementById('rawBox');
              const status = document.getElementById('status');
              try{
                const res = await fetch(PACKAGES_PATH, {cache:'no-store'});
                if(!res.ok) throw new Error('HTTP '+res.status);
                const text = await res.text();
                status.textContent = 'Tải xong.';
                raw.textContent = text;
                const blocks = text.split(/\n\n+/).map(s=>s.trim()).filter(Boolean);
                const rows = [];
                for(const b of blocks){
                  const map = {};
                  for(const line of b.split('\n')){
                    const i = line.indexOf(':');
                    if(i>0){ map[line.slice(0,i).trim()] = line.slice(i+1).trim(); }
                  }
                  const name = map['Package']||'';
                  const ver  = map['Version']||'';
                  const arch = map['Architecture']||'';
                  const size = map['Size']||'';
                  const desc = map['Description']||'';
                  const file = map['Filename']||'';
                  rows.push(`<tr><td>${name}</td><td>${ver}</td><td>${arch}</td><td>${size}</td><td>${desc}</td><td>${file ? `<a href="${file}">.deb</a>` : ''}</td></tr>`);
                }
                body.innerHTML = rows.join('') || `<tr><td colspan="6"><em>Chưa có gói.</em></td></tr>`;
              }catch(e){
                status.textContent = 'Lỗi tải Packages: '+e.message;
                body.innerHTML = `<tr><td colspan="6"><em>Không đọc được Packages.</em></td></tr>`;
              }
            }
            loadPackages();
            </script>
          </body>
          </html>
          HTML

      - name: Add .nojekyll and debug listing
        run: |
          touch out/.nojekyll
          echo "==== OUT TREE ===="
          ls -R out

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
