name: Deploy APT repo to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'debs/**'
      - 'ipa/**'
      - 'scripts/**'
      - 'style.css'
      - '.github/workflows/deploy.yml'
      - 'generate-index.sh'
      - 'CydiaIcon.png'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare build dir
        run: |
          rm -rf out && mkdir -p out/repo out/ipa
          [ -f style.css ] && cp style.css out/ || true
          [ -f CydiaIcon.png ] && cp CydiaIcon.png out/ || true
          # copy debs
          if ls debs/*.deb >/dev/null 2>&1; then
            cp debs/*.deb out/repo/
          else
            echo "INFO: no debs"
          fi
          # copy ipa (giữ cấu trúc con nếu có)
          if ls ipa/*.ipa >/dev/null 2>&1 || ls ipa/*/*.ipa >/dev/null 2>&1; then
            rsync -a --include="*/" --include="*.ipa" --exclude="*" ipa/ out/ipa/
          else
            echo "INFO: no ipa"
          fi

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev jq

      - name: Generate Packages (and gzip)
        run: |
          cd out/repo
          dpkg-scanpackages . /dev/null > Packages
          gzip -fk Packages
          cd -

      - name: Generate IPA manifest (ipa/manifest.json + SHA256SUMS + index.html)
        shell: bash
        run: |
          set -e
          cd out/ipa
          # checksums
          if find . -type f -name '*.ipa' | grep -q .; then
            find . -type f -name '*.ipa' -print0 | xargs -0 sha256sum > SHA256SUMS
          else
            : > SHA256SUMS
          fi

          # manifest IPA
          cat > manifest.json <<'JSON'
          { "items": [
          JSON
          first=1
          while IFS= read -r -d '' f; do
            size=$(stat -c%s "$f" 2>/dev/null || stat -f%z "$f")
            sum=$(grep "  $f$" SHA256SUMS | awk '{print $1}')
            url="${f#./}"
            file=$(basename "$f")
            [ $first -eq 0 ] && echo "," >> manifest.json
            first=0
            printf '  { "file":%s,"size":%s,"sha256":%s,"url":%s }\n' \
              "$(jq -Rn --arg v "$file" '$v')" \
              "$size" \
              "$(jq -Rn --arg v "$sum" '$v')" \
              "$(jq -Rn --arg v "$url" '$v')" >> manifest.json
          done < <(find . -type f -name '*.ipa' -print0 | sort -z)
          echo "] }" >> manifest.json

          # trang index cho IPA
          cat > index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
          <title>IPA Downloads</title>
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
          <main class="container my-4">
            <h1 class="h4">IPA Downloads</h1>
            <p class="text-muted">Danh sách .ipa (auto-build).
              <a href="manifest.json">manifest.json</a> ·
              <a href="SHA256SUMS">SHA256SUMS</a>
            </p>
            <div class="table-responsive">
              <table class="table table-sm table-striped">
                <thead><tr><th>Tên file</th><th>Kích thước</th><th>SHA256</th><th>Tải</th></tr></thead>
                <tbody id="tbody"><tr><td colspan="4">Đang tải…</td></tr></tbody>
              </table>
            </div>
            <a class="btn btn-secondary" href="../">← Trang chủ</a>
          </main>
          <script>
          async function main(){
            try{
              const res = await fetch('manifest.json', {cache:'no-store'});
              const data = await res.json();
              const tbody = document.getElementById('tbody'); tbody.innerHTML='';
              if(!data.items.length){ tbody.innerHTML='<tr><td colspan="4"><em>Chưa có IPA.</em></td></tr>'; return; }
              for(const it of data.items){
                const tr = document.createElement('tr');
                const mb = it.size ? (it.size/1e6).toFixed(2)+' MB' : '';
                tr.innerHTML = `<td class="text-break">${it.file}</td><td>${mb}</td><td class="text-break">${it.sha256||''}</td><td><a href="${it.url}" download>Download</a></td>`;
                tbody.appendChild(tr);
              }
            }catch(e){
              document.getElementById('tbody').innerHTML = `<tr><td colspan="4"><em>Lỗi tải manifest.</em></td></tr>`;
            }
          }
          main();
          </script>
          HTML

      - name: Generate ROOT manifest.json (IPA + DEB)
        shell: bash
        run: |
          set -e
          cd out
          # sha256 cho debs
          if find repo -maxdepth 1 -type f -name '*.deb' | grep -q .; then
            (cd repo && sha256sum *.deb > SHA256SUMS)
          else
            : > repo/SHA256SUMS || true
          fi

          PACK=repo/Packages
          touch "$PACK"

          cat > manifest.json <<'JSON'
          { "items": [
          JSON
          first=1

          # add IPA
          if [ -d ipa ]; then
            while IFS= read -r -d '' f; do
              size=$(stat -c%s "ipa/$f" 2>/dev/null || stat -f%z "ipa/$f")
              sum=$( (cd ipa && grep "  ./$f$" SHA256SUMS | awk '{print $1}') )
              url="ipa/$f"
              file=$(basename "$f")
              catg="${f%/*}"; [ "$catg" = "$f" ] && catg="uncategorized" || catg="${catg##*/}"
              [ $first -eq 0 ] && echo "," >> manifest.json
              first=0
              printf '  { "type":"ipa","category":%s,"file":%s,"size":%s,"sha256":%s,"url":%s }\n' \
                "$(jq -Rn --arg v "$catg" '$v')" \
                "$(jq -Rn --arg v "$file" '$v')" \
                "$size" \
                "$(jq -Rn --arg v "$sum" '$v')" \
                "$(jq -Rn --arg v "$url" '$v')" >> manifest.json
            done < <(cd ipa && find . -type f -name '*.ipa' -printf '%P\0' | sort -z)
          fi

          # add DEB từ Packages
          awk -v RS='' '{
            pkg=""; ver=""; arch=""; file=""; size="";
            n=split($0, a, /\n/);
            for(i=1;i<=n;i++){
              split(a[i], kv, ": "); k=kv[1]; v=substr(a[i], index(a[i],": ")+2);
              if(k=="Package") pkg=v;
              else if(k=="Version") ver=v;
              else if(k=="Architecture") arch=v;
              else if(k=="Filename") file=v;
              else if(k=="Size") size=v;
            }
            if(file!=""){
              printf "PKG\t%s\t%s\t%s\t%s\t%s\n", pkg, ver, arch, size, file;
            }
          }' "$PACK" | while IFS=$'\t' read -r tag pkg ver arch size file; do
            [ -f "$file" ] || continue
            sum=$( (cd repo && grep "  $(basename "$file")$" SHA256SUMS | awk '{print $1}') )
            [ $first -eq 0 ] && echo "," >> manifest.json
            first=0
            printf '  { "type":"deb","package":%s,"version":%s,"arch":%s,"size":%s,"sha256":%s,"url":%s,"file":%s }\n' \
              "$(jq -Rn --arg v "$pkg" '$v')" \
              "$(jq -Rn --arg v "$ver" '$v')" \
              "$(jq -Rn --arg v "$arch" '$v')" \
              "$size" \
              "$(jq -Rn --arg v "$sum" '$v')" \
              "$(jq -Rn --arg v "$file" '$v')" \
              "$(jq -Rn --arg v "$(basename "$file")" '$v')" >> manifest.json
          done

          echo "] }" >> manifest.json

      - name: Generate index.html (Bootstrap) with links
        run: |
          cat > out/index.html <<'HTML'
          <!doctype html>
          <html lang="vi">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Ninh Repo</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
            <link rel="icon" href="CydiaIcon.png">
          </head>
          <body>
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
              <div class="container">
                <a class="navbar-brand" href="./">Ninh Repo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div id="nav" class="collapse navbar-collapse">
                  <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="packages.html">Tweaks (viewer)</a></li>
                    <li class="nav-item"><a class="nav-link" href="repo/Packages">/repo/Packages</a></li>
                    <li class="nav-item"><a class="nav-link" href="ipa/">IPA</a></li>
                    <li class="nav-item"><a class="nav-link" href="manifest.json">Manifest tổng</a></li>
                  </ul>
                </div>
              </div>
            </nav>
            <header class="py-5 bg-light border-bottom">
              <div class="container">
                <h1 class="display-6 fw-bold">Kho APT Repo của Ninh (GitHub Pages)</h1>
                <p class="lead mb-4">Tuyển tập các deb, ipa dành cho hệ iOS cổ, mời anh em <code>vọc</code>.</p>
                <div>
                  <a class="btn btn-primary btn-lg me-2" href="packages.html">Xem Packages</a>
                  <a class="btn btn-success btn-lg me-2" href="ipa/">Xem IPA</a>
                  <a class="btn btn-outline-secondary btn-lg" href="repo/Packages">Tải Packages</a>
                </div>
              </div>
            </header>
            <main class="container my-5">
              <p>Manifest: <a href="ipa/manifest.json">IPA</a> · <a href="manifest.json">Tổng (IPA + DEB)</a></p>
            </main>
            <footer class="py-4 bg-dark text-white-50">
              <div class="container text-center small">© 2025 <a href="/">Ninh Repo</a></div>
            </footer>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
          </body>
          </html>
          HTML

      - name: Add .nojekyll & debug tree
        run: |
          touch out/.nojekyll
          echo "==== OUT TREE ====" && ls -R out

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
