# .github/workflows/update-apt-repo.yaml
# PHIÊN BẢN SIÊU TỐI GIẢN ĐỂ DEBUG LỖI CÚ PHÁP

name: Build and Deploy APT Repo (Debug)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev gpg

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}

      - name: Create directory structure
        run: mkdir -p public/debs

      - name: Copy essential files
        run: |
          cp -r debs/* public/debs/
          echo "${{ secrets.PUBLIC_KEY }}" > public/KEY.gpg

      - name: Build APT Repository
        run: |
          cd public
          dpkg-scanpackages --multiversion . > Packages
          gzip -c9 Packages > Packages.gz
          apt-ftparchive release . > Release
          gpg --clearsign -u "${{ steps.import_gpg.outputs.email }}" -o InRelease Release
          gpg -abs -u "${{ steps.import_gpg.outputs.email }}" -o Release.gpg Release
          cd ..
      
      # --- BƯỚC TẠO HTML ĐÃ ĐƯỢC ĐƠN GIẢN HÓA TỐI ĐA ---
      - name: Generate simplified index.html (Debug)
        run: |
          echo "--- Starting simplified HTML generation ---"
          # Tạo file và ghi phần đầu
          echo '<!DOCTYPE html><html><head><title>Ninh Repo - Package List</title></head><body>' > public/index.html
          echo '<h1>List of .deb Files Found</h1>' >> public/index.html
          
          # Vòng lặp đơn giản để kiểm tra xem file có được tìm thấy không
          if [ -d "debs" ]; then
            find debs -type f -name "*.deb" | while read -r deb; do
              # Chỉ in tên file để kiểm tra vòng lặp có chạy không
              echo "<p>Found file: ${deb}</p>" >> public/index.html
            done
          else
            echo '<p>ERROR: Directory "debs" not found!</p>' >> public/index.html
          fi
          
          # Ghi phần cuối
          echo '</body></html>' >> public/index.html
          echo "--- Simplified HTML generation complete. ---"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
