# .github/workflows/update-apt-repo.yaml
# PHIÊN BẢN CUỐI CÙNG - KHÔNG DÙNG ACTION BÊN THỨ BA, TỰ BUILD BẰNG LỆNH LINUX

name: Build and Deploy APT Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Lấy mã nguồn về
      - name: Checkout main branch
        uses: actions/checkout@v4

      # Bước 2: Cài đặt các công cụ cần thiết
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev gpg

      # Bước 3: Import GPG key để ký repo
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}

      # Bước 4: Tạo cấu trúc thư mục để deploy
      - name: Create directory structure
        run: mkdir -p public/debs

      # Bước 5: Copy các file tĩnh (trang web, css, file .deb) vào thư mục public
      - name: Copy static files and debs
        run: |
          cp -r debs/* public/debs/
          cp style.css public/
          # Copy GPG Public Key để người dùng có thể tải về
          echo "${{ secrets.PUBLIC_KEY }}" > public/KEY.gpg

      # Bước 6: Xây dựng APT Repository bằng lệnh tiêu chuẩn
      - name: Build APT Repository
        run: |
          echo "--- Building Packages file ---"
          # Đi vào thư mục public để làm việc
          cd public
          # Tạo file Packages và Packages.gz
          dpkg-scanpackages --multiversion . > Packages
          gzip -c9 Packages > Packages.gz
          
          echo "--- Building Release file ---"
          # Tạo file Release, InRelease, và Release.gpg
          apt-ftparchive release . > Release
          gpg --clearsign -u "${{ steps.import_gpg.outputs.email }}" -o InRelease Release
          gpg -abs -u "${{ steps.import_gpg.outputs.email }}" -o Release.gpg Release
          echo "--- APT Repo build complete ---"
          # Quay lại thư mục gốc
          cd ..
      
      # Bước 7: Tạo trang index.html với danh sách gói
      - name: Generate professional index.html
        run: |
          # Bước này sẽ tạo file index.html và đặt nó vào thư mục public
          # (Nội dung script tương tự như trước, chỉ thay đổi đường dẫn output)
          cat <<EOF > public/index.html
          <!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Repo của ${{ github.repository_owner }}</title><link rel="stylesheet" href="style.css"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet"></head><body><div class="container"><header><h1>${{ github.event.repository.name }}</h1><p>Kho lưu trữ APT được host trên GitHub Pages.</p></header><main><section class="installation"><h2>Hướng dẫn cài đặt</h2><pre><code># Thêm GPG Key
          curl -sS --compressed "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/${{ github.event.repository.name }}.gpg >/dev/null
          # Thêm Repo
          echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/${{ github.event.repository.name }}.gpg] https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/ /" | sudo tee /etc/apt/sources.list.d/${{ github.event.repository.name }}.list
          # Cập nhật
          sudo apt update</code></pre></section><section class="packages"><h2>Danh sách các gói</h2><div class="package-list">
          EOF

          for deb in debs/*.deb; do
            if [ -f "\$deb" ]; then
              PACKAGE_NAME=\$(dpkg-deb -f "\$deb" Package)
              VERSION=\$(dpkg-deb -f "\$deb" Version)
              DESCRIPTION=\$(dpkg-deb -f "\$deb" Description | head -n 1)
              cat <<EOF >> public/index.html
          <div class="package-item"><div class="package-info"><h3>\$PACKAGE_NAME</h3><p style="color: #aaa; font-size: 0.9em;">Phiên bản: \$VERSION</p><p>\$DESCRIPTION</p></div></div>
          EOF
            fi
          done

          cat <<EOF >> public/index.html
          </div></section></main><footer><p>&copy; $(date +%Y) ${{ github.repository_owner }}. Hosted on GitHub Pages.</p></footer></div></body></html>
          EOF

      # Bước 8: Deploy thư mục 'public' lên nhánh gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Tên và email của người commit bot
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
