# .github/workflows/update-apt-repo.yaml
# PHIÊN BẢN CUỐI CÙNG - ĐÃ SỬA LỖI ĐƯỜNG DẪN QUÉT FILE .DEB

name: Build and Deploy APT Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev gpg apt-utils unzip

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}

      - name: Create directory structure for deployment
        run: mkdir -p public

      - name: Copy essential files to public directory
        run: |
          # Copy các thư mục chứa gói tin
          if [ -d "debs" ]; then cp -r debs public/; fi
          if [ -d "ipas" ]; then cp -r ipas public/; fi
          
          # Copy các file tĩnh khác
          if [ -f "style.css" ]; then cp style.css public/; fi
          if [ -f "CydiaIcon.png" ]; then cp CydiaIcon.png public/; fi
          echo "${{ secrets.PUBLIC_KEY }}" > public/KEY.gpg

      # --- BƯỚC NÀY ĐÃ ĐƯỢC SỬA LẠI ---
      - name: Build APT Repository for Cydia
        run: |
          cd public
          
          # Quét các gói trong thư mục 'debs' và ghi kết quả vào file 'Packages'
          echo "Scanning .deb files from 'debs' directory..."
          dpkg-scanpackages --multiversion debs /dev/null > Packages
          gzip -c9 Packages > Packages.gz
          
          # Tạo file cấu hình cho Release
          cat <<EOF > apt.conf
          APT::FTPArchive::Release {
            Origin "Ninh's Repo";
            Label "Ninh's Repo";
            Suite "stable";
            Version "1.0";
            Codename "ios";
            Architectures "iphoneos-arm";
            Components "main";
            Description "Kho lưu trữ các gói deb và ứng dụng cho thiết bị iOS của Ninh.";
          };
          EOF
          
          # Tạo file Release từ file Packages đã có
          echo "Generating Release file..."
          apt-ftparchive -c apt.conf release . > Release
          
          # Ký file Release
          gpg --clearsign -u "${{ steps.import_gpg.outputs.email }}" -o InRelease Release
          gpg -abs -u "${{ steps.import_gpg.outputs.email }}" -o Release.gpg Release
          
          echo "--- APT Repo for Cydia build complete ---"
          cd ..
      
      - name: Generate index.html page
        run: ./generate-index.sh

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'