# .github/workflows/update-apt-repo.yaml
# PHIÊN BẢN HOÀN CHỈNH CUỐI CÙNG

name: Build and Deploy APT Repo

on:
  push:
    branches: [ main ]
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Cấp quyền cho workflow để có thể push lên nhánh gh-pages
    permissions:
      contents: write

    steps:
      # Bước 1: Lấy mã nguồn về
      - name: Checkout main branch
        uses: actions/checkout@v4

      # Bước 2: Cài đặt các công cụ cần thiết
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev gpg

      # Bước 3: Import GPG key để ký repo
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}

      # Bước 4: Tạo cấu trúc thư mục để deploy
      - name: Create directory structure
        run: mkdir -p public/debs

      # Bước 5: Copy các file cần thiết vào thư mục public
      - name: Copy essential files
        run: |
          # Dùng if để tránh lỗi nếu không có file .deb nào
          if [ -n "$(ls -A debs/*.deb 2>/dev/null)" ]; then
            cp -r debs/* public/debs/
          fi
          # Chỉ copy style.css nếu nó tồn tại
          if [ -f "style.css" ]; then
            cp style.css public/
          fi
          # Xuất public key để người dùng có thể tải về
          echo "${{ secrets.PUBLIC_KEY }}" > public/KEY.gpg

      # Bước 6: Xây dựng APT Repository bằng lệnh Linux tiêu chuẩn
      - name: Build APT Repository
        run: |
          cd public
          dpkg-scanpackages --multiversion . > Packages
          gzip -c9 Packages > Packages.gz
          apt-ftparchive release . > Release
          gpg --clearsign -u "${{ steps.import_gpg.outputs.email }}" -o InRelease Release
          gpg -abs -u "${{ steps.import_gpg.outputs.email }}" -o Release.gpg Release
          cd ..
      
      # Bước 7: Chạy kịch bản rời để tạo trang index.html
      - name: Generate index.html page
        run: ./generate-index.sh

      # Bước 8: Deploy thư mục 'public' lên nhánh gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
