# .github/workflows/update-apt-repo.yaml
# PHIÊN BẢN NÂNG CẤP - HỖ TRỢ CYDIA

name: Build and Deploy APT Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev gpg apt-utils unzip

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}

      - name: Create directory structure
        run: mkdir -p public/debs

      - name: Copy essential files
        run: |
          if [ -n "$(ls -A debs/*.deb 2>/dev/null)" ]; then
            cp -r debs/* public/debs/
          fi
          # Thêm logic để copy file IPA nếu có
          if [ -d "ipas" ]; then
            mkdir -p public/ipas
            cp -r ipas/* public/ipas/
          fi
          if [ -f "style.css" ]; then
            cp style.css public/
          fi
          # --- THÊM DÒNG NÀY ĐỂ COPY ICON ---
          if [ -f "CydiaIcon.png" ]; then
            cp CydiaIcon.png public/
          fi
          echo "${{ secrets.PUBLIC_KEY }}" > public/KEY.gpg

      # --- BƯỚC NÀY ĐÃ ĐƯỢC NÂNG CẤP ---
      - name: Build APT Repository for Cydia
        run: |
          cd public
          
          # Tạo file Packages
          dpkg-scanpackages --multiversion . > Packages
          gzip -c9 Packages > Packages.gz
          
          # Tạo file cấu hình tạm thời cho file Release
          cat <<EOF > apt.conf
          APT::FTPArchive::Release {
            Origin "Ninh's Repo";
            Label "Ninh's Repo";
            Suite "stable";
            Version "1.0";
            Codename "ios";
            Architectures "iphoneos-arm";
            Components "main";
            Description "Kho lưu trữ các gói deb và ứng dụng cho thiết bị iOS của Ninh.";
          };
          EOF
          
          # Tạo file Release sử dụng file cấu hình ở trên
          apt-ftparchive -c apt.conf release . > Release
          
          # Ký file Release
          gpg --clearsign -u "${{ steps.import_gpg.outputs.email }}" -o InRelease Release
          gpg -abs -u "${{ steps.import_gpg.outputs.email }}" -o Release.gpg Release
          
          echo "--- APT Repo for Cydia build complete ---"
          cd ..
      
      - name: Generate index.html page
        run: ./generate-index.sh

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'